language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
branches:
  only:
  - master
before_script:
  - npm install -g coveralls lighthouse
  - npm install
script:
  - npm test
  - npm run build-css
  - npm run build
after_script:
  - npm run coverage
  - cat ./coverage/lcov.info | coveralls
before_deploy:
  - zip -r star-wars-galaxy.zip build/*
  - git config --local user.name "civa86"
  - git config --local user.email "dario.civallero@gmail.com"
  - git tag "TAG..."
deploy:
  # PUBLISH ON FIREBASE
  - provider: firebase
    token:
      secure: "YOUR ENCRYPTED token"
    message: "your message"
    skip_cleanup: true
  # UPLOAD RELEASE ARTIFACT
  - provider: releases
    api_key: "GITHUB OAUTH TOKEN"
    file: "star-wars-galaxy.zip"
    skip_cleanup: true
# AFTER DEPLOY: Audits and upload to gist
after_deploy:
  - lighthouse --output json --output-path lighthouse.report.json <URL>
  - export REPORT=`cat lighthouse.report.json`
  - curl -v --request PATCH -H "Authorization: token $GH_TOKEN" -d '{"description": "updated star wars lighthouse report", "files": {"star-wars-galaxy.lighthouse.report.json": {"content": "$REPORT"}}}' https://api.github.com/gists/f01219ac55a43bb2d52657f959a98acc
env:
  global:
  - secure: put github token...
  - secure: put coveralls token...

