language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
branches:
  only:
  - master
before_script:
  - npm install -g coveralls
  # - npm install -g coveralls lighthouse
script:
  - npm test
  - npm run build-css
  - npm run build
after_script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run coverage && cat ./coverage/lcov.info | coveralls; fi'
# before_deploy:
#   - export VERSION="`node -p -e "require('./package.json').version"`"
#   - zip -r star-wars-galaxy.zip build/*
#   - git config --local user.name "civa86"
#   - git config --local user.email "dario.civallero@gmail.com"
#   - git tag "v.$VERSION.build.$TRAVIS_BUILD_NUMBER"
# deploy:
#   # PUBLISH ON FIREBASE
#   - provider: firebase
#     token:
#       secure: "YOUR ENCRYPTED token"
#     message: "your message"
#     skip_cleanup: true
#   # UPLOAD RELEASE ARTIFACT
#   - provider: releases
#     api_key: "$GH_TOKEN"
#     file: "star-wars-galaxy.zip"
#     skip_cleanup: true
# # AFTER DEPLOY: Audit and upload to gist
# after_deploy:
#   - lighthouse --output json --output-path lighthouse.report.json <URL>
#   - export REPORT=`cat lighthouse.report.json`
#   - "curl -v --request PATCH -H \"Authorization: token $GH_TOKEN\" -d \"{\"files\": {\"$GIST_FILE\": {\"content\": \"$REPORT\"}}}\" $GIST_URL"
env:
  global:
  - GIST_URL=https://api.github.com/gists/f01219ac55a43bb2d52657f959a98acc
  - GIST_FILE=star-wars-galaxy.lighthouse.report.json
  # - secure: create and encrypt GH_TOKEN
